name: client
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>= 3.19.3 <4.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter_rust_bridge: ^2.0.0-dev.28
  #flutter_rust_bridge_utils:
  #  path: frb_utils
  server:
    path: rust_builder
  freezed_annotation: ^2.4.1
  grpc: ^3.2.4
  network_info_plus: ^4.1.0+1
  protobuf: ^3.1.0
  flutter: 
    sdk: flutter
  lints: ^3.0.0
  ffi: ^2.1.2
dev_dependencies: 
  build_runner: ^2.4.4
  ffigen: ^11.0.0
  flutter_lints: ^3.0.1
  freezed: ^2.1.0+1
  pubspec_dependency_sorter: ^1.0.4
  test: ^1.21.4
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true